server {
    listen 80;
    server_name _;

    # Paramètres globaux de proxy
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cookie_flags ~ nosecure;

    # Pre-registration UI (default)
    # location / {
    #     proxy_pass http://pre-reg-ui:8080/;
    # }

    location / {
        proxy_pass http://admin-ui:8080/;
    }

    # Pre-registration services
    # location /preregistration/ {
    #     proxy_pass http://pre-registration-application-service:9090/preregistration/;
    #     proxy_cookie_flags Authorization nosecure;
    #     proxy_cookie_flags canAuthorise nosecure;
    # }

    # # Keycloak - UNIFIED (une seule location)
    # location /keycloak/ {
    #     proxy_pass http://keycloak:8080/;
    #     proxy_buffer_size 128k;
    #     proxy_buffers 4 256k;
    #     proxy_busy_buffers_size 256k;
    # }

    # Admin UI
    location /admin-ui/ {
        proxy_pass http://admin-ui:8080/admin-ui/;
    }

    # Auditmanager service 
    location /v1/auditmanager/ {
        proxy_pass http://kernel-auditmanager-service:8081/v1/auditmanager/;
    }

    # Admin service
    location /v1/admin/ {
        proxy_pass http://admin-service:8098/v1/admin/;
        proxy_cookie_flags Authorization nosecure;
    }

    # Hotlist service
    location /v1/hotlist/ {
        proxy_pass http://hotlist-service:8095/v1/hotlist/;
    }

    # Syncdata service
    location /v1/syncdata/ {
        proxy_pass http://kernel-syncdata-service:8089/v1/syncdata/;
    }

    # Masterdata service
    location /v1/masterdata/ {
        proxy_pass http://kernel-masterdata-service:8086/v1/masterdata/;
    }

    # Auth service
    location /v1/authmanager/ {
        proxy_pass http://kernel-auth-service:8091/v1/authmanager/;
        proxy_cookie_flags Authorization nosecure;
    }

    # Keymanager service
    # location /v1/keymanager/ {
    #     proxy_pass http://kernel-keymanager-service:8088/v1/keymanager/;
    # }
}