server {
    listen 80;
    proxy_cookie_flags ~ nosecure;
    location / {
        proxy_pass http://pre-reg-ui:8080/;
    }
    location /preregistration/ {
        proxy_pass http://pre-registration-application-service:9090/preregistration/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cookie_flags Authorization nosecure;
        proxy_cookie_flags canAuthorise nosecure;
    }
}
