mosip.auth.adapter.impl.basepackage=io.mosip.kernel.auth.defaultadapter
mosip.kernel.auth.adapter.ssl-bypass=true
mosip.iam.adapter.appid=admin
mosip.iam.adapter.clientid=mosip-admin-client
mosip.iam.adapter.clientsecret=mosip123
mosip.iam.adapter.issuerURL=http://keycloak:8080/auth/realms/mosip
auth.server.admin.issuer.uri=http://keycloak:8080/auth/realms/
mosip.kernel.auth.appids.realm.map={prereg:'preregistration',ida:'mosip',registrationclient:'mosip',regproc:'mosip',partner:'mosip',resident:'mosip',admin:'mosip'}
javax.persistence.jdbc.url=jdbc:postgresql://postgres:5432/mosip_keymgr
javax.persistence.jdbc.user=keymgruser
javax.persistence.jdbc.password=mosip123
mosip.database.ip=postgres
mosip.database.port=5432
mosip.kernel.keymanager.softhsm.config-path=/etc/softhsm/softhsm2.conf
mosip.kernel.keymanager.softhsm.keystore-type=PKCS11
mosip.kernel.keymanager.softhsm.keystore-pass=1234

keycloak.use-resource-role-mappings=false
