mosip.auth.adapter.impl.basepackage=io.mosip.kernel.auth.defaultadapter
mosip.kernel.auth.adapter.ssl-bypass=true
mosip.iam.adapter.appid=admin
mosip.iam.adapter.clientid=mosip-admin-client
mosip.iam.adapter.clientsecret=mosip123
