mosip.auth.adapter.impl.basepackage=io.mosip.kernel.auth.defaultadapter
mosip.kernel.auth.adapter.ssl-bypass=true
mosip.iam.adapter.appid=admin
mosip.iam.adapter.clientid=mosip-admin-client
mosip.iam.adapter.clientsecret=mosip123
mosip.iam.adapter.issuerURL=http://keycloak:8080/auth/realms/mosip
auth.server.admin.issuer.uri=http://keycloak:8080/auth/realms/
mosip.kernel.auth.appids.realm.map={prereg:'preregistration',ida:'mosip',registrationclient:'mosip',regproc:'mosip',partner:'mosip',resident:'mosip',admin:'mosip'}
otpmanager_database_url=jdbc:postgresql://postgres:5432/mosip_kernel?useSSL=false
javax.persistence.jdbc.url=jdbc:postgresql://postgres:5432/mosip_kernel?useSSL=false
javax.persistence.jdbc.user=kerneluser
javax.persistence.jdbc.password=mosip123
javax.persistence.jdbc.driver=org.postgresql.Driver
mosip.database.ip=postgres
mosip.database.port=5432

# Allow prereg client to generate OTP
mosip.role.kernel.otpgenerator=INDIVIDUAL,REGISTRATION_OFFICER,REGISTRATION_SUPERVISOR,REGISTRATION_ADMIN,RESIDENT,prereg
auth.server.admin.allowed.audience=mosip-prereg-client,mosip-admin-client
