mosip.auth.adapter.impl.basepackage=io.mosip.kernel.auth.defaultadapter
mosip.kernel.auth.adapter.ssl-bypass=true
mosip.iam.adapter.appid=admin
mosip.iam.adapter.clientid=mosip-admin-client
mosip.iam.adapter.clientsecret=mosip123
mosip.iam.adapter.issuerURL=http://keycloak:8080/auth/realms/mosip
auth.server.admin.issuer.uri=http://keycloak:8080/auth/realms/
mosip.kernel.auth.appids.realm.map={prereg:'preregistration',ida:'mosip',registrationclient:'mosip',regproc:'mosip',partner:'mosip',resident:'mosip',admin:'mosip'}
mosip.kernel.prid.sequence-limit=3
mosip.kernel.prid.length=14
mosip.kernel.prid.test-digit=1
mosip.kernel.prid.repeating-limit=2
mosip.kernel.prid.repeating-block-limit=3
javax.persistence.jdbc.url=jdbc:postgresql://postgres:5432/mosip_kernel
javax.persistence.jdbc.user=kerneluser
javax.persistence.jdbc.password=mosip123
mosip.database.ip=postgres
mosip.database.port=5432
